"""adds_google_id_to_users_table

Revision ID: 0149240ef859
Revises: 150ac22ba8c3
Create Date: 2017-10-17 16:14:37.519805

"""

# revision identifiers, used by Alembic.
revision = '0149240ef859'
down_revision = '150ac22ba8c3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_id')
    ### end Alembic commands ###
