"""add users to annotation tasks

Revision ID: 164255ac9373
Revises: e85102f15a03
Create Date: 2017-03-23 21:50:59.352514

"""

# revision identifiers, used by Alembic.
revision = '164255ac9373'
down_revision = 'e85102f15a03'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_tasks', sa.Column('user_ids', postgresql.ARRAY(sa.BigInteger(), as_tuple=sa.ForeignKey('users.id')), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_tasks', 'user_ids')
    ### end Alembic commands ###
