"""adds search queries and user search queries

Revision ID: 260a12dc08ae
Revises: 164255ac9373
Create Date: 2017-04-27 20:14:01.713578

"""

# revision identifiers, used by Alembic.
revision = '260a12dc08ae'
down_revision = '164255ac9373'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_queries',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('search_args_hash', sa.Text(), nullable=True),
    sa.Column('search_args', postgresql.JSON(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('search_count', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('search_query_id_seq')))
    op.create_index(op.f('ix_search_queries_search_args_hash'), 'search_queries', ['search_args_hash'], unique=True)
    op.create_index(op.f('ix_search_queries_search_count'), 'search_queries', ['search_count'], unique=False)
    op.create_table('user_search_queries',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('search_query_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('user_search_query_id_seq')))
    op.create_index(op.f('ix_user_search_queries_search_query_id'), 'user_search_queries', ['search_query_id'], unique=False)
    op.create_index(op.f('ix_user_search_queries_user_id'), 'user_search_queries', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_search_queries_user_id'), table_name='user_search_queries')
    op.drop_index(op.f('ix_user_search_queries_search_query_id'), table_name='user_search_queries')
    op.drop_table('user_search_queries')
    op.drop_index(op.f('ix_search_queries_search_count'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_search_args_hash'), table_name='search_queries')
    op.drop_table('search_queries')
    ### end Alembic commands ###
