"""add user created documents table

Revision ID: 397de36338cc
Revises: 0292af3cd6ea
Create Date: 2017-02-06 18:11:23.723188

"""

# revision identifiers, used by Alembic.
revision = '397de36338cc'
down_revision = '0292af3cd6ea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_created_documents',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('doc_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('failure_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('doc_details', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('user_created_document_id_seq')))
    op.create_index(op.f('ix_user_created_documents_status'), 'user_created_documents', ['status'], unique=False)
    op.create_index(op.f('ix_user_created_documents_user_id'), 'user_created_documents', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_created_documents_status'), table_name='user_created_documents')
    op.drop_index(op.f('ix_user_created_documents_user_id'), table_name='user_created_documents')
    op.drop_table('user_created_documents')
    ### end Alembic commands ###
