"""adds_user_shared_folders_table

Revision ID: 3d1b65a92a80
Revises: 4e067f29994d
Create Date: 2017-09-29 19:25:31.650278

"""

# revision identifiers, used by Alembic.
revision = '3d1b65a92a80'
down_revision = '4e067f29994d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_shared_folders',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'],),
    sa.ForeignKeyConstraint(['folder_id'], ['user_folders.id'],),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('user_shared_folder_id_seq')))
    op.create_index(op.f('ix_user_shared_folder_user_id'), 'user_shared_folders', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_shared_folder_id'), 'user_shared_folders', ['folder_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_shared_folder_user_id'), table_name='user_shared_folders')
    op.drop_index(op.f('ix_user_shared_folder_id'), table_name='user_shared_folders')
    op.drop_table('user_shared_folders')
    ### end Alembic commands ###
