"""add insights graph

Revision ID: 44ca1259e052
Revises: 700869c6a3d1
Create Date: 2017-07-05 10:34:58.232610

"""

# revision identifiers, used by Alembic.
revision = '44ca1259e052'
down_revision = '700869c6a3d1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights_tables',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSON(), nullable=True),
    sa.Column('csv_table', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_tables_name'), 'insights_tables', ['name'], unique=False)
    op.create_index(op.f('ix_insights_tables_slug'), 'insights_tables', ['slug'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_tables_slug'), table_name='insights_tables')
    op.drop_index(op.f('ix_insights_tables_name'), table_name='insights_tables')
    op.drop_table('insights_tables')
    ### end Alembic commands ###
