"""rename annotation task groups

Revision ID: 47c1ef50d01a
Revises: 8a59ba074e88
Create Date: 2017-11-28 18:06:42.631514

"""

# revision identifiers, used by Alembic.
revision = '47c1ef50d01a'
down_revision = '8a59ba074e88'
branch_labels = None
depends_on = None

from alembic import op
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('annotation_task_groups', 'annotation_task_topic_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('annotation_task_topic_groups', 'annotation_task_groups')
    # ### end Alembic commands ###
