"""add new fields to help capture user types

Revision ID: 48c9a4cbc81d
Revises: 238e49d46a5d
Create Date: 2016-09-19 21:55:30.183460

"""

# revision identifiers, used by Alembic.
revision = '48c9a4cbc81d'
down_revision = '238e49d46a5d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('discipline', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('industry', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('level', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.drop_column('users', 'industry')
    op.drop_column('users', 'discipline')
    op.drop_column('users', 'company')
    ### end Alembic commands ###
