"""add user followed entities

Revision ID: 524d305ee49a
Revises: a359a216ead7
Create Date: 2016-09-27 16:46:01.349007

"""

# revision identifiers, used by Alembic.
revision = '524d305ee49a'
down_revision = 'a359a216ead7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_followed_entities',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('following', sa.Boolean(), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('user_followed_entity_id_seq')))
    op.create_index('user_id_following_entity_type_index', 'user_followed_entities', ['user_id', 'following', 'entity_type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_following_entity_type_index', table_name='user_followed_entities')
    op.drop_table('user_followed_entities')
    ### end Alembic commands ###
