"""added notes and admin notes fields to topic_annotation table

Revision ID: 56979a27451f
Revises: a4440a4fc99b
Create Date: 2017-11-12 20:55:30.313372

"""

# revision identifiers, used by Alembic.
revision = '56979a27451f'
down_revision = 'a4440a4fc99b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_annotations', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('topic_annotations', sa.Column('notes', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_annotations', 'notes')
    op.drop_column('topic_annotations', 'admin_notes')
    ### end Alembic commands ###
