"""contributor_and_gold_tags_annnotation_tasks

Revision ID: 56a20b784a7b
Revises: ff19d4afe4d9
Create Date: 2017-12-13 13:25:47.867767

"""

# revision identifiers, used by Alembic.
revision = '56a20b784a7b'
down_revision = 'ff19d4afe4d9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_tasks', sa.Column('include_gold_annotations', sa.Boolean(), nullable=True))
    op.add_column('annotation_tasks', sa.Column('is_contributor_task', sa.Boolean(), nullable=True))
    op.add_column('annotation_tasks', sa.Column('is_training_task', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_annotation_tasks_include_gold_annotations'), 'annotation_tasks', ['include_gold_annotations'], unique=False)
    op.create_index(op.f('ix_annotation_tasks_is_contributor_task'), 'annotation_tasks', ['is_contributor_task'], unique=False)
    op.create_index(op.f('ix_annotation_tasks_is_training_task'), 'annotation_tasks', ['is_training_task'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_tasks_is_training_task'), table_name='annotation_tasks')
    op.drop_index(op.f('ix_annotation_tasks_is_contributor_task'), table_name='annotation_tasks')
    op.drop_index(op.f('ix_annotation_tasks_include_gold_annotations'), table_name='annotation_tasks')
    op.drop_column('annotation_tasks', 'is_training_task')
    op.drop_column('annotation_tasks', 'is_contributor_task')
    op.drop_column('annotation_tasks', 'include_gold_annotations')
    # ### end Alembic commands ###
