"""add unique constraint to user emails

Revision ID: 59f532bb2197
Revises: 95483633db38
Create Date: 2017-05-25 20:09:03.044170

"""

# revision identifiers, used by Alembic.
revision = '59f532bb2197'
down_revision = '95483633db38'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    ### end Alembic commands ###
