"""scrub_db

Revision ID: 654843b2efc5
Revises: 1bacb517b0a9
Create Date: 2016-08-03 10:08:36.083946

"""

# revision identifiers, used by Alembic.
revision = '654843b2efc5'
down_revision = '1bacb517b0a9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column('bookmarked', sa.Boolean(), nullable=True))
    op.create_index('user_id_bookmark_index', 'user_documents', ['user_id', 'bookmarked'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_bookmark_index', table_name='user_documents')
    op.drop_column('user_documents', 'bookmarked')
    ### end Alembic commands ###
