"""linkedin

Revision ID: 67e4f755b1c6
Revises: 583744f10bd0
Create Date: 2017-09-18 19:07:09.154162

"""

# revision identifiers, used by Alembic.
revision = '67e4f755b1c6'
down_revision = 'ee45c910fdcb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin')
    ### end Alembic commands ###
