"""add boolean field for arbitrary queries

Revision ID: 68816d628c0b
Revises: 260a12dc08ae
Create Date: 2017-04-28 21:14:29.245106

"""

# revision identifiers, used by Alembic.
revision = '68816d628c0b'
down_revision = '260a12dc08ae'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_queries', sa.Column('is_arbitrary_query', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_search_queries_is_arbitrary_query'), 'search_queries', ['is_arbitrary_query'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_queries_is_arbitrary_query'), table_name='search_queries')
    op.drop_column('search_queries', 'is_arbitrary_query')
    ### end Alembic commands ###
