"""Add data column

Revision ID: 6ed7477c3222
Revises: c755d6d8f748
Create Date: 2017-05-10 15:46:25.110457

"""

# revision identifiers, used by Alembic.
revision = '6ed7477c3222'
down_revision = 'c755d6d8f748'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_flagged_documents', sa.Column('data', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_flagged_documents', 'data')
    ### end Alembic commands ###
