"""add suspended fields and index email

Revision ID: 8766bdadc553
Revises: 68816d628c0b
Create Date: 2017-05-01 15:32:03.054396

"""

# revision identifiers, used by Alembic.
revision = '8766bdadc553'
down_revision = '68816d628c0b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('suspended', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('suspended_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'suspended_reason')
    op.drop_column('users', 'suspended')
    ### end Alembic commands ###
