"""add tables for contributor points

Revision ID: 8bf4e291389c
Revises: 7cc7f13762f3
Create Date: 2017-05-11 16:50:53.533972

"""

# revision identifiers, used by Alembic.
revision = '8bf4e291389c'
down_revision = '7cc7f13762f3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributor_point_types',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=True),
    sa.Column('point_group_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('points_per_action', sa.BigInteger(), nullable=True),
    sa.Column('actions_per_week', sa.BigInteger(), nullable=True),
    sa.Column('points_per_month', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('contributor_point_type_id_seq')))
    op.create_index(op.f('ix_contributor_point_types_point_group_name'), 'contributor_point_types', ['point_group_name'], unique=False)
    op.create_index(op.f('ix_contributor_point_types_short_name'), 'contributor_point_types', ['short_name'], unique=False)
    op.create_table('user_contributor_points',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('contributor_point_type_id', sa.BigInteger(), nullable=True),
    sa.Column('num_points', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_point_type_id'], ['contributor_point_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('user_contributor_point_id_seq')))
    op.create_index(op.f('ix_user_contributor_points_contributor_point_type_id'), 'user_contributor_points', ['contributor_point_type_id'], unique=False)
    op.create_index(op.f('ix_user_contributor_points_user_id'), 'user_contributor_points', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_contributor_points_user_id'), table_name='user_contributor_points')
    op.drop_index(op.f('ix_user_contributor_points_contributor_point_type_id'), table_name='user_contributor_points')
    op.drop_table('user_contributor_points')
    op.drop_index(op.f('ix_contributor_point_types_short_name'), table_name='contributor_point_types')
    op.drop_index(op.f('ix_contributor_point_types_point_group_name'), table_name='contributor_point_types')
    op.drop_table('contributor_point_types')
    ### end Alembic commands ###
