"""add updated_at indexes

Revision ID: 95483633db38
Revises: 6ed7477c3222
Create Date: 2017-05-17 16:22:17.770565

"""

# revision identifiers, used by Alembic.
revision = '95483633db38'
down_revision = '6ed7477c3222'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_document_updated_at_index', 'user_documents', ['updated_at'], unique=False)
    op.create_index('user_search_queries_updated_at_index', 'user_search_queries', ['updated_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_search_queries_updated_at_index', table_name='user_search_queries')
    op.drop_index('user_document_updated_at_index', table_name='user_documents')
    ### end Alembic commands ###
