"""annotation jobs user diff arbitrary text

Revision ID: 9e2410d7be5b
Revises: 0149240ef859
Create Date: 2017-10-23 13:55:36.630987

"""

# revision identifiers, used by Alembic.
revision = '9e2410d7be5b'
down_revision = '0149240ef859'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_jobs', sa.Column('arbitrary_tags', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('annotation_jobs', sa.Column('user_difficulty', sa.Text(), nullable=True))
    op.create_index(op.f('ix_annotation_jobs_user_difficulty'), 'annotation_jobs', ['user_difficulty'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_jobs_user_difficulty'), table_name='annotation_jobs')
    op.drop_column('annotation_jobs', 'user_difficulty')
    op.drop_column('annotation_jobs', 'arbitrary_tags')
    ### end Alembic commands ###
