"""add new multiple_field column to save flagged by contributor fields

Revision ID: ac6e4c784f98
Revises: 268c688e8232
Create Date: 2017-08-14 11:03:15.034562

"""

# revision identifiers, used by Alembic.
revision = 'ac6e4c784f98'
down_revision = '268c688e8232'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_flagged_documents', sa.Column('multiple_field', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_flagged_documents', 'multiple_field')
    ### end Alembic commands ###
