"""add_user_folders

Revision ID: d695e6da69b0
Revises: b30ee377fbe3
Create Date: 2016-09-28 14:11:28.975756

"""

# revision identifiers, used by Alembic.
revision = 'd695e6da69b0'
down_revision = 'b30ee377fbe3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_folders',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_folder_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('user_folder_id_seq')))
    op.create_index(op.f('ix_user_folder_name'), 'user_folders', ['name'], unique=False)
    op.create_index(op.f('ix_user_folder_parent_folder_id'), 'user_folders', ['parent_folder_id'], unique=False)
    op.create_index(op.f('ix_user_folder_user_id'), 'user_folders', ['user_id'], unique=False)
    op.create_table('user_folder_documents',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_folder_id', sa.BigInteger(), nullable=True),
    sa.Column('doc_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_folder_id'], ['user_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('user_folder_doc_id_seq')))
    op.create_index(op.f('ix_user_folder_document_doc_id'), 'user_folder_documents', ['doc_id'], unique=False)
    op.create_index(op.f('ix_user_folder_document_user_folder_id'), 'user_folder_documents', ['user_folder_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_folder_document_user_folder_id'), table_name='user_folder_documents')
    op.drop_index(op.f('ix_user_folder_document_doc_id'), table_name='user_folder_documents')
    op.drop_table('user_folder_documents')
    op.drop_index(op.f('ix_user_folder_user_id'), table_name='user_folders')
    op.drop_index(op.f('ix_user_folder_parent_folder_id'), table_name='user_folders')
    op.drop_index(op.f('ix_user_folder_name'), table_name='user_folders')
    op.drop_table('user_folders')
    ### end Alembic commands ###
