"""updates_payments_columns

Revision ID: ee45c910fdcb
Revises: 583744f10bd0
Create Date: 2017-09-19 14:50:49.253230

"""

# revision identifiers, used by Alembic.
revision = 'ee45c910fdcb'
down_revision = '583744f10bd0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('recurring', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('status', sa.Text(), nullable=True))
    op.add_column('subscriptions', sa.Column('status_reason', sa.Text(), nullable=True))
    op.add_column('subscriptions', sa.Column('suspension_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('user_cancellation_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('period_count', sa.BigInteger(), nullable=True))
    op.add_column('subscriptions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('subscriptions', sa.Column('modified_by_user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_subscriptions_modified_by_user_id'), 'subscriptions', ['modified_by_user_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'users', ['modified_by_user_id'], ['id'])
    ### end Alembic commands ###

    # change existing column name 'active' to 'curent'
    op.alter_column('subscriptions', 'active', new_column_name='latest')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_modified_by_user_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'user_cancellation_date')
    op.drop_column('subscriptions', 'period_count')
    op.drop_column('subscriptions', 'suspension_date')
    op.drop_column('subscriptions', 'status_reason')
    op.drop_column('subscriptions', 'status')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'notes')
    op.drop_column('subscriptions', 'modified_by_user_id')
    op.drop_column('subscriptions', 'expiration_date')
    op.drop_column('plans', 'recurring')
    ### end Alembic commands ###

    op.alter_column('subscriptions', 'latest', new_column_name='active')
