"""add_act_word_counts

Revision ID: efcd5b3e0204
Revises: 48c9a4cbc81d
Create Date: 2016-09-26 12:23:21.315000

"""

# revision identifiers, used by Alembic.
revision = 'efcd5b3e0204'
down_revision = '48c9a4cbc81d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('act_word_counts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('act_id', sa.BigInteger(), nullable=False),
    sa.Column('build_name', sa.Text(), nullable=False),
    sa.Column('month_counts', postgresql.JSON(), nullable=True),
    sa.Column('month_tfidf', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('act_word_count_id_seq')))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('act_word_counts')
    ### end Alembic commands ###
