"""adds_permission_columns_to_shared_folders

Revision ID: f3c7bb1e9977
Revises: 3d1b65a92a80
Create Date: 2017-10-02 11:55:53.897379

"""

# revision identifiers, used by Alembic.
revision = 'f3c7bb1e9977'
down_revision = '3d1b65a92a80'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_shared_folders', sa.Column('owner', sa.Boolean(), nullable=True))
    op.add_column('user_shared_folders', sa.Column('editor', sa.Boolean(), nullable=True))
    op.add_column('user_shared_folders', sa.Column('viewer', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_shared_folders', 'owner')
    op.drop_column('user_shared_folders', 'editor')
    op.drop_column('user_shared_folders', 'viewer')
    ### end Alembic commands ###
