"""improve groups table and topic iding

Revision ID: ff19d4afe4d9
Revises: 47c1ef50d01a
Create Date: 2017-11-28 18:10:46.351441

"""

# revision identifiers, used by Alembic.
revision = 'ff19d4afe4d9'
down_revision = '47c1ef50d01a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_task_topic_groups', sa.Column('active_topic_annotation_model_id', sa.BigInteger(), nullable=True))
    op.add_column('annotation_task_topic_groups', sa.Column('gold_annotator_user_ids', postgresql.ARRAY(sa.BigInteger(), as_tuple=sa.ForeignKey('users.id')), nullable=True))
    op.add_column('annotation_task_topic_groups', sa.Column('topic_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_annotation_task_topic_groups_name'), 'annotation_task_topic_groups', ['name'], unique=False)
    op.create_index(op.f('ix_annotation_task_topic_groups_topic_id'), 'annotation_task_topic_groups', ['topic_id'], unique=False)
    op.drop_index('ix_annotation_task_groups_name', table_name='annotation_task_topic_groups')
    op.add_column('topic_annotations', sa.Column('topic_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_topic_annotations_topic_id'), 'topic_annotations', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_annotations_topic_id'), table_name='topic_annotations')
    op.drop_column('topic_annotations', 'topic_id')
    op.create_index('ix_annotation_task_groups_name', 'annotation_task_topic_groups', ['name'], unique=False)
    op.drop_index(op.f('ix_annotation_task_topic_groups_topic_id'), table_name='annotation_task_topic_groups')
    op.drop_index(op.f('ix_annotation_task_topic_groups_name'), table_name='annotation_task_topic_groups')
    op.drop_column('annotation_task_topic_groups', 'topic_id')
    op.drop_column('annotation_task_topic_groups', 'gold_annotator_user_ids')
    op.drop_column('annotation_task_topic_groups', 'active_topic_annotation_model_id')
    # ### end Alembic commands ###
