"""add user saved searches

Revision ID: ff7d37775df1
Revises: 967bdad10d92
Create Date: 2016-10-13 21:06:33.859974

"""

# revision identifiers, used by Alembic.
revision = 'ff7d37775df1'
down_revision = '967bdad10d92'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_saved_searches',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('search_args', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(CreateSequence(Sequence('user_saved_search_id_seq')))
    op.create_index(op.f('ix_user_saved_searches_user_id'), 'user_saved_searches', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_saved_searches_user_id'), table_name='user_saved_searches')
    op.drop_table('user_saved_searches')
    ### end Alembic commands ###
